### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by ghost** [ComputersMania/hotel-reservation-app#1]
![logo logotype icon](https://user-images.githubusercontent.com/36993664/38157136-a86f3148-348c-11e8-8767-2178d33e898a.jpg)

Hi,

I have made a icon to help you in your project and to better present the program you have developed. If you want any change, you can contact me without hesitation. I hope you use it.

_*Place Icon and Do not Disturb Icon combined._

Görsel İletişim

**Comment by ComputersMania** [comment]
Thanks man.
Am I free to use them?
Do you have a version with higher resolution of them?

**Comment by ComputersMania** [comment]
Maybe in svg format

**Comment by ghost** [comment]
Of course, you can use it as you like. I will send it in an hour.

**Comment by ghost** [comment]
You can get the file you want here, if you have another request, you can write to me. I have my e-mail address on my profile.

https://drive.google.com/open?id=1Q9WRcNR46qmgqnzpSvJlWNNyW4Qpo1yP

**Comment by ghost** [comment]
This logo is license under (http://creativecommons.org/licenses/by/4.0) Creative Commons Attribution 4.0 International License
